chain_width = 175
fn_call_width = 120
fn_params_layout = "Compressed"
fn_single_line = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Crate"
max_width = 185
overflow_delimited_expr = true
reorder_imports = true
struct_lit_width = 50
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true